version: 0.2
phases:
  build:
    commands:
      - echo Entered the build phase...
      - ./gradlew clean build
      - echo Build completed successfully
artifacts:
  files:
    - build/libs/*.jar
  name: employeeManagement-$(grep version gradle.properties|cut -d= -f2)-$(date +%Y-%m-%d-%H-%M-%S)
  discard-paths: yes